### ISSUE TITLE
To avoid opening sqlite connection in every api calls

### ISSUE THREAD

**Issue by viggy28** [spinup-host/spinup#100]
In `/listcluster` https://github.com/spinup-host/spinup/blob/585d955905e2d69c1d7f68f5736b5695b0c61191/api/list_cluster.go#L35 
we are invoking NewDb() to create a new SQLite connection every time when the endpoint is hit.

In `/metrics` we have a package level `db` variable which gets initialized once (for the first time)
https://github.com/spinup-host/spinup/blob/585d955905e2d69c1d7f68f5736b5695b0c61191/metrics/metrics.go#L41
Using package-level variables are discouraged in general.

**Comment by idoqo** [comment]
@viggy28 can we close this now?

**Comment by viggy28** [comment]
Yes we should. We can improve the variable names as you suggested. Perhaps that's a separate issue.
