### ISSUE TITLE
unable to create Postgres service if the image doesn't exist

### ISSUE THREAD

**Issue by viggy28** [spinup-host/spinup#103]
@skant7 reported an issue that where the first time I create a cluster of a specific version it gets created with no problem
but if I create a cluster again of a different version the daemon doesn't seem to find the image tag
here's what the logs say

![Screenshot from 2022-03-26 20-36-20](https://user-images.githubusercontent.com/15543619/160303561-a5d8cc6d-2133-4ca2-9775-935bf45e0e22.png)
 
What I think the problem is https://github.com/spinup-host/spinup/blob/6dd74211db5b867b141b1ebe29f4253ce4fe5670/internal/dockerservice/dockerservice.go#L111 expects the image to be pulled already.

**Comment by viggy28** [comment]
Is it good to be closed @skant7 ?

**Comment by skant7** [comment]
I tried testing it locally, the problem still exists. There might be something more we are missing out here.

**Comment by viggy28** [comment]
@skant7 confirmed that the issue no longer exists.
