### ISSUE TITLE
Slack link is no longer active

### ISSUE THREAD

**Issue by Ghibranalj** [spinup-host/spinup#112]
Hey,
I saw u/vira28's comment on joining this development team. Your project seems interesting. I read your contribution guide on `CONTRIBUTING.md` but the slack link seems to be dead.

Sorry if this isn't a proper issue. I want to keep my reddit profile somewhat anonymous, so i dont want anyone connecting my reddit profile to my github profile so i couldn't just dm  u/vira28.

Thanks

**Comment by viggy28** [comment]
u/vira28 or u/viggy28 (I go by both in the Internet) here.

Thanks @Ghibranalj for your interest on Spinup. Fixing the issue on https://github.com/spinup-host/spinup/pull/113
