### ISSUE TITLE
Add support for enabling/disabling monitoring of clusters

### ISSUE THREAD

**Issue by idoqo** [spinup-host/spinup#76]
At the moment, cluster monitoring can be enabled on creation (using the monitoring field in the request body).

We'd like to extend this to allow users to enable monitoring for an already running cluster. Similarly, they should be able to disable monitoring for a cluster that already has monitoring enabled.

The goal is to expose endpoints that:
- Toggles the monitoring status of the cluster (disable if enabled, enable if disabled).

**Comment by idoqo** [comment]
We already have some work with monitoring and metrics. E.g, @viggy28  added support for exporting internal SpinUp metrics to Prometheus. I think we can use that as a basis for proper monitoring support. Here's what I'm thinking for now:

- A global toggle on the frontend that can disable/enable monitoring. If this toggle is "ON", we will run a Prometheus instance alongside spinup and all metrics gets sent there (both for Spinup and the database instances).
- A Toggle present when creating a new db instance (we already have this) but users should only be able to enable this if system monitoring is enabled (the global toggle above). If system monitoring is OFF, we simply alert the user to turn it ON first if they want "per-database" monitoring.
- Users can only toggle "per-database" monitoring as long as "global" monitoring is enabled.

Also, looks like postgres_exporter allows one instance to monitor multiple databases like [this](https://github.com/prometheus-community/postgres_exporter/issues/267#issuecomment-483638914), so when disabling monitoring for  a db, we can simply remove the connection string of that db from the config.

**Comment by viggy28** [comment]
instead of making the user turn on global monitoring explicitly when they want to enable DB monitoring, we will enable that implicitly (as discussed in our slack).
